project:
  type: website
  output-dir: docs

website:
  title: "승학"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Project
        href: project.qmd
      - text: Blog 
        href: blog.qmd
        
      

format:
  html:
    theme: cosmo
    toc: true



