project:
  type: website
  output-dir: docs

website:
  title: "DS 승학"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
      - text: hw1.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



