project:
  type: website
  output-dir: docs

website:
  title: "DS 승학"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd
      - text: Blog 
        href: posts/blog.qmd
        
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



