---
title: "LS 빅데이터 스쿨 Homework 2"
author: "승학"
date: "2024-07-16"
categories: [bigdata]
---


## Q 4-1 자동차 배기량에 따라 고속도로 연비가 다른지 알아보려고 합니다. displ(배기량)이 4이하인 자동차와 5이상인 자동차 중 어떤 자동차의 hwy(고속도로 연비) 평균이 더 높은지 알아보세요.

```{python}
import pandas as pd
mpg = pd.read_csv("data/mpg.csv")
mpg

mpg_a = mpg.query('displ <= 4')
mpg_b = mpg.query('displ >= 5')

mpg_a['hwy'].mean()
mpg_b['hwy'].mean()

```


## Q 4-2 자동차 제조 회사에 따라 도시 연비가 어떻게 다른지 알아보려고 합니다. 'audi'와 'toyota' 중 어느 manufacturer(자동차 제조 회사)의 cty(도시 연비) 평균이 더 높은지 알아보세요.

```{python}

mpg_audi = mpg.query('manufacturer == "audi"')
mpg_toyota = mpg.query('manufacturer == "toyota"')

mpg_audi["cty"].mean()
mpg_toyota["cty"].mean()

```


## Q 4-3 'chevrolet', 'ford', 'honda' 자동차의 고속도로 연비 평균을 알아보려고 합니다. 세 회사의 데이터를 추출한 다음 hwy 전체 평균을 구해 보세요.

```{python}

mpg_new = mpg.query('manufacturer in ["chevrolet", "ford", "honda"]')
mpg_new["hwy"].mean()

```


## Q 5-1 'audi'에서 생산한 자동차 중에 어떤 자동차 모델의 hwy(고속도로 연비)가 높은지 알아보려고 합니다. 'audi'에서 생산한 자동차 중 hwy가 1~5위에 해당하는 자동차의 데이터를 출력하세요.

```{python}

mpg.query("manufacturer == 'audi'")\
   .sort_values('hwy', ascending = False)\
   .head()



```


## Q 6-1 mpg 데이터 복사본을 만들고, cty와 hwy를 더한 '합산 연비 변수'를 추가하세요.

```{python}

mpg_new = mpg.copy()
mpg_new = mpg_new.assign(total = mpg["cty"] + mpg["hwy"])
mpg_new

```


## 6-2 앞에서 만든 '합산 연비 변수'를 2로 나눠 '평균 연비 변수'를 추가하세요.

```{python}

mpg_new = mpg_new.assign(mean = mpg_new["total"] / 2)
mpg_new

```


## 6-3 '평균 연비 변수'가 가장 높은 자동차 3종의 데이터를 출력하세요.

```{python}

mpg_new.sort_values("mean", ascending = False).head(3)


```


## 6-4 1~3번 문제를 해결할 수 있는 하나로 연결된 pandas 구문을 만들어 실행해 보세요. 데이터는 복사본 대신 mpg 원본을 이용하세요.

```{python}

mpg.assign(total = lambda x : x["cty"] + x["hwy"],
            mean = lambda x : x["total"]/2)\
            .sort_values("mean", ascending = False)\
            .head(3)



```

## 7-1 mpg 데이터의 cty(도시 연비)와 hwy(고속도로 연비) 간에 어떤 관계가 있는지 알아보려고 합니다. x축은 cty, y축은 hwy로 된 산점도를 만들어 보세요.

```{python}

import seaborn as sns
import pandas as pd

mpg = pd.read_csv("data/mpg.csv")
mpg
mpg_df = sns.scatterplot(data = mpg, x = "cty", y = "hwy")
mpg_df

```

## 7-2 미국의 지역별 인구통계 정보를 담은 midwest.csv를 이용해 전체 인구와 아시아인 인구 간에 어떤 관계가 있는지 알아보려고 합니다. x축은 poptotal(전체 인구), y축은 popasian(아시아인 인구)으로 된 산점도를 만들어 보세요. 전체 인구는 50만 명 이하, 아시아인 인구는 1만 명 이하인 지역만 산점도에 표시되게 설정하세요.

```{python}



```

